name: getserver_web_api
version: 1.0.0
description: A new Get Server application.
environment: 
  sdk: '>=3.2.4'

dependencies: 
  get_server: 1.2.1

dev_dependencies: 
  pedantic: 1.11.1
  test: 1.25.2

